:arrow_up: Update package imports and error handling.
Revised import statements in the codebase
to use relative imports for better compatibility.
This includes changes in `media_parser/parsers/reddit.py`,
`media_parser/parsers/tiktok.py`, and more files.
Additionally, introduced improvements in error handling
while performing database operations.

This ensures that the application does not crash when a MongoDB operation fails; instead, it logs the error for debugging purposes.

Lastly, updated the project with the latest package versions for enhanced stability and performance.
This commit aims to improve code maintainability and resilience.

Signed-off-by: Jag_k <me@jagk.dev>

diff --git a/.github/workflows/pypi-publish.yml b/.github/workflows/pypi-publish.yml
--- a/.github/workflows/pypi-publish.yml
+++ b/.github/workflows/pypi-publish.yml
@@ -11,16 +11,44 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v2
+
       - uses: actions/setup-python@v2
         with:
           python-version: "3.11"
+
       - name: Install poetry
         uses: abatilo/actions-poetry@v2.0.0
         with:
-          poetry-version: "1.5.1"
+          poetry-version: "1.6.1"
+
       - name: Publish to PyPI
         env:
           PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
         run: |
           poetry config pypi-token.pypi $PYPI_TOKEN
-          poetry publish --build
+          poetry publish --build --no-interaction && echo "published=1" >> "$GITHUB_ENV" || echo "published=0" >> "$GITHUB_ENV"
+
+      - name: Check if published
+        run: |
+          if [ "$published" = "1" ]; then
+            echo "Published to PyPI"
+          else
+            echo "Failed to publish to PyPI"
+            exit 1
+          fi
+#      - name: Build Dash Docset
+#        run: |
+#          poetry run python -m dash_docs.tools.generate_docset
+
+      - name: Make release with docset
+        uses: softprops/action-gh-release@v1
+        with:
+#          files: |
+#            dash-docset.tgz
+          tag_name: ${{ github.ref }}
+#          body: |
+#            Dash Docset for Dash ${{ github.ref }}
+          draft: false
+          prerelease: false
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
